### ISSUE TITLE
KeyError with nested patternProperties

### ISSUE THREAD

**Issue by j616** [horejsek/python-fastjsonschema#28] opened 2018-09-20 13:51 UTC
When an object using patternProperties is further down the tree than another patternProperties field you get a KeyError.

Example schema:-
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "patternProperties": {
        "^foo:": {
            "type": "object",
            "properties": {
                "baz": {
                    "type": "object",
                    "patternProperties": {
                        "^b": {
                            "type": "object"
                        }
                    }
                },
                "bit": {
                    "type": "object"
                }
            },
            "required": [
                "baz",
                "bit"
            ]
        }
    }
}
```

Example document to validate against it :- 
```json
{
    "foo:bar": {
        "baz": {
            "bat": {
            }
        },
        "bit": {
        }
    }
}
```

This results in :- 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 38, in validate
KeyError: 'bit'
```

The following schema where the second patternProperties is replaced with a regular properties validates correctly:- 
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "patternProperties": {
        "^foo:": {
            "type": "object",
            "properties": {
                "baz": {
                    "type": "object",
                    "properties": {
                        "bat": {
                            "type": "object"
                        }
                    }
                },
                "bit": {
                    "type": "object"
                }
            },
            "required": [
                "baz",
                "bit"
            ]
        }
    }
}
```

The following where the first patterProperties is replaced also validates correctly:- 
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "foo:bar": {
            "type": "object",
            "properties": {
                "baz": {
                    "type": "object",
                    "patternProperties": {
                        "^b": {
                            "type": "object"
                        }
                    }
                },
                "bit": {
                    "type": "object"
                }
            },
            "required": [
                "baz",
                "bit"
            ]
        }
    }
}
```

**Comment by j616** [comment] 2018-09-21 09:41
Doing some more digging with this. Turned out I was still on 1.6. Now on 2.3. The test case above no longer fails for me but I'm still getting the same sort of error on slightly more complex cases. I'll try and put together a new test case.

**Comment by j616** [comment] 2018-09-21 10:47
I don't have much more useful info yet, but it does seem that the problem is non-deterministic. Running the same time multiple times results in different key errors (in the example above, they would be with keys at the baz/bit level) or occasionally results in the document validating successfully...

**Comment by j616** [comment] 2018-09-26 09:16
Any chance someone could take a look at this?

**Comment by FrederikP** [comment] 2018-09-26 10:15
Just discovered a bug related to this by using your example schema and data and debugging into the generated code (using compile_to_code). The key error is reproducable for me.
There is an issue with variables being overwritten, because in python the scopes of variables are not very strict. I'm not very familiar with the code, but maybe I can find a way to fix this.

This doesn't seem to be a problem that is only related to patternproperties, but I'm not sure.

**Comment by horejsek** [comment] 2018-09-26 11:56
I plan to look at it tomorrow.

**Comment by FrederikP** [comment] 2018-09-26 12:07
Okay, my first naive idea was to use something like:
```{name}_key, {name}_val```
but the name template variable seems to be only made for use in strings and not in the code as it can depend on one more formatting step.

I'll let you look into it @horejsek . If you have any questions about what I found out, let me know. When debugging the generated code using the example from this issue, the problem becomes clear quite quickly.

**Comment by horejsek** [comment] 2018-09-26 13:14
Thanks @FrederikP, you found the bug. :-) This same problem was on more places. It's fixed in master. I plan to do more stuff tomorrow, do you want to release is today or can you wait till tomorrow, @j616?

**Closed by horejsek** 2018-09-26 13:14 UTC
