### ISSUE TITLE
fastjsonschema fails if fields that are 'required' are not passed in even though they have defaults set

### ISSUE THREAD

**Issue by theahura** [horejsek/python-fastjsonschema#148] opened 2022-05-02 21:39 UTC
If I run the following minimum repro: 
```python
import fastjsonschema

schema = {
    '$schema': 'http://json-schema.org/draft-07/schema#',
    '$id': '/foo',
    'type': 'object',
    'properties': {
        'name': {
            'const': 1,
            'default': 1
        },
    },
    'required': ['name'],
}

validator = fastjsonschema.compile(schema, use_default=True)

print(validator({}))
```
I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    print(validator({}))
  File "<string>", line 10, in validate__foo
fastjsonschema.exceptions.JsonSchemaValueException: data must contain ['name'] properties
```
even though there is a default field set. Given the schema, I would expect this to succeed validation and print
```
{ 'name': 1 }
```

**Comment by horejsek** [comment] 2022-06-13 11:27
Duplicate of https://github.com/horejsek/python-fastjsonschema/issues/106

**Closed by horejsek** 2022-06-13 11:27 UTC
Labels: bug
