### ISSUE TITLE
new breaking behavior in 2.15.3

### ISSUE THREAD

**Issue by instil-richard** [horejsek/python-fastjsonschema#137] opened 2022-01-09 21:42 UTC
it appears that some change released in 2.15.3 causes a validation of the URLs in the json schema definition (this was not behavior previously that I am aware.) 

I dont have a fix but I'm calling it out here as a critical issue someone must investigate or rollback latest release to 2.15.2 before more people get latest for a minor release and things break. 

Traceback for your info:

```
lib/python3.9/site-packages/fastjsonschema/ref_resolver.py\", line 62, in resolve_remote\n   req = urlopen(uri)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py\", line 214, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py\", line 517, in open\n    response = self._open(req, data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py\", line 534, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n    result = func(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py\", line 1385, in https_open\n    return self.do_open(http.client.HTTPSConnection, req,\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py\", line 1345, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>","exception_name":"URLError"}
```

**Comment by horejsek** [comment] 2022-01-10 07:26
Can you be more specific? Because I think the issue is not the 2.15.3 release. At least this is what was changed: https://github.com/horejsek/python-fastjsonschema/compare/v2.15.2...v2.15.3

**Comment by horejsek** [comment] 2022-02-25 12:17
Closing. Please re-open if problem is still around with more details.

**Closed by horejsek** 2022-02-25 12:17 UTC
