### ISSUE TITLE
Undefined format error with 2.14

### ISSUE THREAD

**Issue by earonesty** [horejsek/python-fastjsonschema#64] opened 2019-10-08 19:47 UTC
We relied on undefined formats (format="base64", etc.).   We use them to create custom transcoders that can encode/decode JSON (instead of formats, we use transcodes).  Our code works with 2.13.   FYI: New release no longer works.   No big deal, b/c I can just add all my formatters with lamda: True to fix.... (or change the name of the key i use).

```
...
  File "site-packages/fastjsonschema/__init__.py", line 165, in compile
  File "site-packages/fastjsonschema/draft04.py", line 68, in global_state
  File "site-packages/fastjsonschema/generator.py", line 74, in global_state
  File "site-packages/fastjsonschema/generator.py", line 115, in _generate_func_code
  File "vidamessage/schema/__init__.py", line 27, in generate_func_code
  File "site-packages/fastjsonschema/generator.py", line 129, in generate_func_code
  File "site-packages/fastjsonschema/generator.py", line 139, in generate_validation_function
  File "site-packages/fastjsonschema/generator.py", line 152, in generate_func_code_block
  File "site-packages/fastjsonschema/draft06.py", line 35, in _generate_func_code_block
  File "site-packages/fastjsonschema/generator.py", line 170, in run_generate_functions
  File "site-packages/fastjsonschema/draft04.py", line 462, in generate_properties
  File "site-packages/fastjsonschema/generator.py", line 152, in generate_func_code_block
  File "site-packages/fastjsonschema/draft06.py", line 35, in _generate_func_code_block
  File "site-packages/fastjsonschema/generator.py", line 170, in run_generate_functions
  File "site-packages/fastjsonschema/draft04.py", line 268, in generate_format
fastjsonschema.exceptions.JsonSchemaDefinitionException: Undefined format %s
```

**Comment by horejsek** [comment] 2019-10-08 20:38
Hi. Thanks for the feedback. Can you share complete example?

**Comment by earonesty** [comment] 2019-10-08 20:46
This is the original code, with tests at the bottom: https://gist.github.com/earonesty/29e65d9161f812c8088d60c7c5892315

**Comment by horejsek** [comment] 2019-10-09 06:53
This is intended behaviour, not a bug.

But there is definitely bug with the message, usage of %s with format. Fixed in master.

**Closed by horejsek** 2019-10-09 06:53 UTC
