### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Stranger6667** [horejsek/python-fastjsonschema#111] opened 2021-01-30 17:39 UTC
Hello! 

I was benchmarking `fastjsonschema` against other Python implementations and at some point, `fastjsonschema` took too much memory (~30 GB) and I killed the process.

**Schema**: Official Swagger [JSON Schema](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json)
**Instance**: Kubernetes [API definition](https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/kubernetes.io/v1.10.0/swagger.yaml) from API.guru
**Interpreter**: CPython 3.9.1 with `platform.platform()` as `Linux-5.10.11-arch1-1-x86_64-with-glibc2.32`

Other implementations (`jsonschema` and `jsonschema-rs`) didn't demonstrate high memory usage on the same input.

**Dependencies**:

`pip install fastjsonschema==2.14.5  requests==2.25.1 PyYAML==5.4.1`

**Code to reproduce**:

```python
import fastjsonschema
import requests
import yaml
import time

try:
    from yaml import CSafeLoader as Loader
except ImportError:
    from yaml import SafeLoader as Loader

SCHEMA_URL = "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json"
INSTANCE_URL = "https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/kubernetes.io/v1.10.0/swagger.yaml"
ITERATIONS_NUMBER = 10

SCHEMA = requests.get(SCHEMA_URL).json()
INSTANCE = yaml.load(requests.get(INSTANCE_URL).content, Loader=Loader)

validate = fastjsonschema.compile(SCHEMA)

for _ in range(ITERATIONS_NUMBER):
    start = time.time()
    validate(INSTANCE)
    print(f"Iteration time: {time.time() - start}")
```

Output:

```
Iteration time: 0.1041560173034668
Iteration time: 0.12305545806884766
Iteration time: 0.16190171241760254
Iteration time: 0.2381150722503662
Iteration time: 0.438570499420166
Iteration time: 0.8084230422973633
Iteration time: 1.4931752681732178
Iteration time: 2.8855996131896973
Iteration time: 5.7769176959991455
Iteration time: 11.246583461761475
```

Here is the memory usage plotted with `memory-profiler==0.58.0`

![fastjsonschema-memory-usage](https://user-images.githubusercontent.com/1236561/106363443-db0f8080-6328-11eb-89c6-1e6ec8ce5cb2.png)

For comparison, this is the memory usage of `jsonschema==3.2.0`:

Code is almost the same (the validator is compiled):

```python
import jsonschema
import requests
import yaml

try:
    from yaml import CSafeLoader as Loader
except ImportError:
    from yaml import SafeLoader as Loader

SCHEMA_URL = "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json"
INSTANCE_URL = "https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/kubernetes.io/v1.10.0/swagger.yaml"
ITERATIONS_NUMBER = 10

SCHEMA = requests.get(SCHEMA_URL).json()
INSTANCE = yaml.load(requests.get(INSTANCE_URL).content, Loader=Loader)

validate = jsonschema.validators.validator_for(SCHEMA)(SCHEMA)

for _ in range(ITERATIONS_NUMBER):
    validate.validate(INSTANCE)
```

![jsonschema-memory-usage](https://user-images.githubusercontent.com/1236561/106363533-6b4dc580-6329-11eb-8029-11613287ed7e.png)

Unfortunately, I didn't track down what exactly causes the leak (my assumption is that validating the same instance should not linearly increase the memory usage)

Cheers

**Comment by hh-h** [comment] 2021-01-31 15:08
This is somehow related to this line of code https://github.com/horejsek/python-fastjsonschema/blob/8d06a05a0672465437d009afcafa45e14eac1cdf/fastjsonschema/draft04.py#L474

![image](https://user-images.githubusercontent.com/8166963/106388320-ffce2b80-63ee-11eb-9afb-b23deba82d40.png)

it seems it only affected swagger2.0 spec, so I'm not interested in fixing it, sorry :(

**Comment by Stranger6667** [comment] 2021-01-31 16:41
> it seems it only affected swagger2.0 spec

It is not Swagger specific, such behavior could happen in any schema that contains recursive refs + `default`. When the memory consumption is slow enough, it leads to `RecursionError` instead. Consider the following schema:

```python
{
    "properties": {
        "node": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/properties/node",
                    "default": {},
                },
            },
        },
    },
}
```

Instance - `{"node": {}}`

After 100 iterations, the original instance is mutated:

```{'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {'node': {}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
```

Setting the number of iterations to a value >= than the interpreter recursion cap leads to a `RecursionError`.

**Comment by horejsek** [comment] 2021-02-01 06:57
Thanks for investigation. It's indeed due to defaults. But that's intended behaviour. If you don't want this issue, simply don't use defaults. I understand that not everyone likes that it works that way and therefore there is opened #65 to make it optional. Closing this one.

**Closed by horejsek** 2021-02-01 06:57 UTC

**Comment by Stranger6667** [comment] 2021-02-01 06:59
> simply don't use defaults.

Unfortunately, the source of schemas & instances is out of my control. Looking forward to #65!

**Comment by horejsek** [comment] 2021-02-01 07:03
For now, you could recursively iterate the schema and remove all defaults keys from third party schema. Will make for #65 higher priority.

**Comment by horejsek** [comment] 2021-02-01 17:58
I just pushed new version with `use_default` option. Default is still `True` to be compatible, but you can fall back to set it to `False`.

**Comment by Stranger6667** [comment] 2021-02-01 18:08
Thank you very much! :)
