### ISSUE TITLE
Fail on complex schema with nested oneOf

### ISSUE THREAD

**Issue by thormick** [horejsek/python-fastjsonschema#132] opened 2021-12-08 14:44 UTC
In the following example `jsonschema` performs the validation as I expect, but `fastjsonschema` fails incorrectly on the `correct` object and succeeds incorrectly on the `also_not_correct` object. It seems to be particularly confused by the last element in the outer `oneOf`, the one with `"myprop": {"enum": ["baz"]}`, if that is deleted then the result is the same as for `jsonschema` (only the `correct_baz` giving a failure). Replacing the `oneOf` in the inner element with `allOf` also seems to make it work alright; I couldn't easily reproduce a similar failure then.

```python
from jsonschema.validators import validator_for
import fastjsonschema

schema = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "myprop": {"enum": ["foo", "bar", "baz"]},
        "extra": {"type": "string"},
        "extra_2": {"type": "string"}
    },
    "oneOf": [{
        "properties": {
            "myprop": {"enum": ["foo"]}
        },
        "allOf": [
            {"not": {"required": ["extra"]}},
            {"not": {"required": ["extra2"]}}]
    }, {
        "properties": {
            "myprop": {"enum": ["bar"]}
        },
        "required": ["extra"],
        "not": {"required": ["extra_2"]}
    }, {
        "properties": {
            "myprop": {"enum": ["baz"]}
        },
        "oneOf": [
            {"required": ["extra"]},
            {"required": ["extra_2"]}]
    }]
}


correct = {"myprop": "foo"}
also_correct = {"myprop": "bar", "extra": "stuff"}
correct_baz = {"myprop": "baz", "extra": "stuff"}
not_correct = {"myprop": "bar"}
also_not_correct = {"myprop": "foo", "extra": "stuff"}


def _fmt_fjs_ex(e):
    return (f'{e.__class__.__qualname__} for JSON object {e.value} on rule {e.rule_definition}: {e}')


def test_OK(fun, format_ex=lambda x: x):
    try:
        print(f'Correct: {fun()}')
    except Exception as ex:
        print(f'OH NO! Exception on correct object: {format_ex(ex)}')


def test_bad(fun, format_ex=lambda x: x):
    try:
        result = fun()
        print(f'OOPS! Failed to find errors in incorrect object: {result}')
    except Exception as ex:
        print(f'Correctly found incorrect object: {format_ex(ex)}')


print("#### Testing with fastjsonschema")

fjs_validator = fastjsonschema.compile(schema)

test_OK(lambda: fjs_validator(correct), _fmt_fjs_ex)
test_OK(lambda: fjs_validator(also_correct), _fmt_fjs_ex)
test_OK(lambda: fjs_validator(correct_baz), _fmt_fjs_ex)
test_bad(lambda: fjs_validator(not_correct), _fmt_fjs_ex)
test_bad(lambda: fjs_validator(also_not_correct), _fmt_fjs_ex)

print("#### Testing with jsonschema")

js_validator = (validator_for(schema))(schema)

test_OK(lambda: js_validator.validate(correct) or correct)
test_OK(lambda: js_validator.validate(also_correct) or also_correct)
test_OK(lambda: js_validator.validate(correct_baz) or correct_baz)
test_bad(lambda: js_validator.validate(not_correct) or not_correct)
test_bad(lambda: js_validator.validate(also_not_correct) or also_not_correct)
```

`fastjsonschema` 2.15.1, `python` 3.8.10.

This is specifically annoying to me since the only reason I need the odd restriction in that last element is for backwards compatibility, otherwise I could have just done the reverse of the middle element, with "require extra_2, don't allow extra", which fastjsonschema handles fine. Presumably that indicates that this is a rare case.

**Comment by horejsek** [comment] 2021-12-12 13:55
Hi, thanks for the report. The issue is nested oneOf or anyOf. The fix is here: https://github.com/horejsek/python-fastjsonschema/commit/d4a5eb2cda2c523849bfba3e828bea5fc16f2ff4

Will be released with the next version.

**Closed by horejsek** 2021-12-12 13:55 UTC

**Comment by thormick** [comment] 2021-12-13 14:48
You're welcome! Thanks for the prompt fix!
